### ISSUE TITLE
Use jsnext:main convention for es2015

### ISSUE THREAD

**Issue by chadhietala** [cerebris/klassy.js#2]
There is a convention we would like to follow in package.json that indicates to consuming systems that the source contains ES2015 modules.  This convention is simply adding a "jsnext:main" key in the package.json that it's value points to the "main" ES2015 file. /cc @stefanpenner

**Comment by dgeb** [comment]
Oh interesting... do you mean this:

```
"jsnext:name": "lib/klassy.js"
```

Or would I substitute the library's name for `name`?

Is this documented somewhere yet, @chadhietala?

**Comment by chadhietala** [comment]
It's not really documented, there are just a couple projects that use the convention. I think we would like to make this more common. @stefanpenner probably might have more background on the convention.

**Comment by dgeb** [comment]
Ah, so you meant `jsnext:main` - now that makes more sense :+1:

**Comment by chadhietala** [comment]
@dgeb yea sorry. :smile:

**Comment by dgeb** [comment]
@chadhietala no prob!

Just published v0.1.3 btw.
